# Generated by Django 3.2.5 on 2021-07-11 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_alter_departamento_options'),
        ('persona', '0004_alter_persona_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Empleado',
        ),
    ]
